//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCentrumSzamlatomb
    {
        public int ID { get; set; }
        public int ICSzamlatombID { get; set; }
        public string Elotag { get; set; }
        public string Utotag { get; set; }
        public Nullable<int> Hasznalt { get; set; }
        public string Nev { get; set; }
    }
}
