//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konstrukcio
    {
        public Konstrukcio()
        {
            this.Elofizetes = new HashSet<Elofizetes>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public int Ar { get; set; }
        public byte Kod { get; set; }
    
        public virtual ICollection<Elofizetes> Elofizetes { get; set; }
    }
}
