//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugyfel
    {
        public Ugyfel()
        {
            this.Elofizetes = new HashSet<Elofizetes>();
        }
    
        public int ID { get; set; }
        public string Nev { get; set; }
        public Nullable<System.DateTime> SzuletesiIdo { get; set; }
        public string SzuletesiHely { get; set; }
        public string Cegszam { get; set; }
        public string AnyjaNeve { get; set; }
        public string CegkepviseloNeve { get; set; }
        public int LepcsohazId { get; set; }
        public string LakohelyEmelet { get; set; }
        public string LakohelyLakas { get; set; }
        public string SzamlazasiCim { get; set; }
        public string Cegszekhely { get; set; }
        public string Okmanyszam { get; set; }
        public string Telefonszam { get; set; }
        public string Bankszamlaszam { get; set; }
        public int ElofizetoEgyeni { get; set; }
        public int IgenybevetelJogcime { get; set; }
        public System.DateTime SzolgaltatasKezdoIdopontja { get; set; }
        public Nullable<System.DateTime> HatarozottIdejuSzolgaltatasVege { get; set; }
        public int MegrendeltCsomagok { get; set; }
        public int DijbefizetesModja { get; set; }
        public int DifbefizetesUtemezese { get; set; }
        public string CsBeszedKod { get; set; }
        public Nullable<int> ICUgyfelID { get; set; }
        public int Befizetve { get; set; }
    
        public virtual ICollection<Elofizetes> Elofizetes { get; set; }
        public virtual Lepcsohaz Lepcsohaz { get; set; }
    }
}
