//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ukdbEntities6 : DbContext
    {
        public ukdbEntities6()
            : base("name=ukdbEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Beallitasok> Beallitasok { get; set; }
        public DbSet<Elofizetes> Elofizetes { get; set; }
        public DbSet<FizetettIdoszak> FizetettIdoszak { get; set; }
        public DbSet<InfoCentrumSzamlatomb> InfoCentrumSzamlatomb { get; set; }
        public DbSet<Konstrukcio> Konstrukcio { get; set; }
        public DbSet<Lepcsohaz> Lepcsohaz { get; set; }
        public DbSet<Operator> Operator { get; set; }
        public DbSet<SchemaInfo> SchemaInfo { get; set; }
        public DbSet<Ugyfel> Ugyfel { get; set; }
    }
}
