//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beallitasok
    {
        public int ID { get; set; }
        public string Cegnev { get; set; }
        public string Adoazonosito { get; set; }
        public string Bankszamlaszam { get; set; }
        public string IcSzamlaUtvonal { get; set; }
    }
}
