//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FizetettIdoszak
    {
        public int ID { get; set; }
        public int ElofizetesID { get; set; }
        public Nullable<System.DateTime> Mettol { get; set; }
        public Nullable<System.DateTime> Meddig { get; set; }
    
        public virtual Elofizetes Elofizetes { get; set; }
    }
}
