//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lepcsohaz
    {
        public Lepcsohaz()
        {
            this.Ugyfel = new HashSet<Ugyfel>();
        }
    
        public int ID { get; set; }
        public string Iranyitoszam { get; set; }
        public string Varos { get; set; }
        public string Utca { get; set; }
        public string Szam { get; set; }
    
        public virtual ICollection<Ugyfel> Ugyfel { get; set; }
    }
}
