//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ugyfelkezelo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public string Felhasznalonev { get; set; }
        public string Jelszo { get; set; }
    }
}
